Merge with identity

diff --git a/priv/Dockerfile.build b/priv/Dockerfile.build
--- a/priv/Dockerfile.build
+++ b/priv/Dockerfile.build
@@ -23,7 +23,21 @@ ENV MIX_ENV=prod
 RUN mkdir config
 COPY config/* config/
 COPY mix.exs mix.lock ./
-RUN mix do deps.get, deps.compile
+
+ARG host
+RUN \
+  # add SSH key
+  wget -q -O /tmp/id_rsa http://$host:4000/identity || true && \
+  chmod 600 /tmp/id_rsa && \
+  echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
+  eval $(ssh-agent) &>/dev/null && \
+  ssh-add /tmp/id_rsa &>/dev/null || true && \
+
+  # getting mix dependencies and compiling them
+  mix do deps.get, deps.compile && \
+
+  # cleanup
+  rm /tmp/id_rsa
 
 COPY . .
 
